<?php

namespace Romeldev\SusaludX12\Beans\Detalle;


use Romeldev\SusaludX12\Beans\AbstractBean;
class InRegAfi271Detalle extends AbstractBean
{
    /** @var string */
    protected $caPaciente = '';
    /** @var string */
    protected $apPaternoPaciente = '';
    /** @var string */
    protected $noPaciente = '';
    /** @var string */
    protected $coPaciente = '';
    /** @var string */
    protected $apMaternoPaciente = '';
    /** @var string */
    protected $tiDocumentoPaciente = '';
    /** @var string */
    protected $nuDocumentoPaciente = '';
    /** @var string */
    protected $coContratoPaciente = '';
    /** @var string */
    protected $esPaciente = '';
    /** @var string */
    protected $tiRegimenPaciente = '';
    /** @var string */
    protected $tiPlanPaciente = '';
    /** @var string */
    protected $coProductoPaciente = '';
    /** @var string */
    protected $coPlanPaciente = '';
    /** @var string */
    protected $nuCarnetPaciente = '';
    /** @var string */
    protected $coVinculoFamPaciente = '';
    /** @var string */
    protected $apCasadaPaciente = '';
    /** @var string */
    protected $deUbigeoPaciente = '';
    /** @var string */
    protected $feNacePaciente = '';
    /** @var string */
    protected $gePaciente = '';
    /** @var string */
    protected $coPaisPaciente = '';
    /** @var string */
    protected $feFallecidoPaciente = '';
    /** @var string */
    protected $feIniAfiliaPaciente = '';
    /** @var string */
    protected $feFinAfiliaPaciente = '';
    /** @var string */
    protected $feFinAtencionPaciente = '';
    /** @var string */
    protected $caAseguradora = '';
    /** @var string */
    protected $coAseguradora = '';
    /** @var string */
    protected $caTitular = '';
    /** @var string */
    protected $apPaternoTitular = '';
    /** @var string */
    protected $noTitular = '';
    /** @var string */
    protected $coTitular = '';
    /** @var string */
    protected $apMaternoTitular = '';
    /** @var string */
    protected $tiDocumentoTitular = '';
    /** @var string */
    protected $nuDocumentoTitular = '';
    /** @var string */
    protected $coEstablecimientoTitular = '';
    /** @var string */
    protected $feFallecidoTitular = '';
    /** @var string */
    protected $coPaisTitular = '';
    /** @var string */
    protected $caContratante = '';
    /** @var string */
    protected $apPaternoContratante = '';
    /** @var string */
    protected $noContratante = '';
    /** @var string */
    protected $apMaternoContratante = '';
    /** @var string */
    protected $tiDocumentoContratante = '';
    /** @var string */
    protected $idReContratante = '';
    /** @var string */
    protected $nuDocumentoContratante = '';
    /** @var string */
    protected $coPaisContratante = '';
}
