<?php

namespace Romeldev\SusaludX12\Beans\Detalle;

class InRegAfi271Detalle
{
    /** @var string */
    public $caPaciente = '';
    /** @var string */
    public $apPaternoPaciente = '';
    /** @var string */
    public $noPaciente = '';
    /** @var string */
    public $coPaciente = '';
    /** @var string */
    public $apMaternoPaciente = '';
    /** @var string */
    public $tiDocumentoPaciente = '';
    /** @var string */
    public $nuDocumentoPaciente = '';
    /** @var string */
    public $coContratoPaciente = '';
    /** @var string */
    public $esPaciente = '';
    /** @var string */
    public $tiRegimenPaciente = '';
    /** @var string */
    public $tiPlanPaciente = '';
    /** @var string */
    public $coProductoPaciente = '';
    /** @var string */
    public $coPlanPaciente = '';
    /** @var string */
    public $nuCarnetPaciente = '';
    /** @var string */
    public $coVinculoFamPaciente = '';
    /** @var string */
    public $apCasadaPaciente = '';
    /** @var string */
    public $deUbigeoPaciente = '';
    /** @var string */
    public $feNacePaciente = '';
    /** @var string */
    public $gePaciente = '';
    /** @var string */
    public $coPaisPaciente = '';
    /** @var string */
    public $feFallecidoPaciente = '';
    /** @var string */
    public $feIniAfiliaPaciente = '';
    /** @var string */
    public $feFinAfiliaPaciente = '';
    /** @var string */
    public $feFinAtencionPaciente = '';
    /** @var string */
    public $caAseguradora = '';
    /** @var string */
    public $coAseguradora = '';
    /** @var string */
    public $caTitular = '';
    /** @var string */
    public $apPaternoTitular = '';
    /** @var string */
    public $noTitular = '';
    /** @var string */
    public $coTitular = '';
    /** @var string */
    public $apMaternoTitular = '';
    /** @var string */
    public $tiDocumentoTitular = '';
    /** @var string */
    public $nuDocumentoTitular = '';
    /** @var string */
    public $coEstablecimientoTitular = '';
    /** @var string */
    public $feFallecidoTitular = '';
    /** @var string */
    public $coPaisTitular = '';
    /** @var string */
    public $caContratante = '';
    /** @var string */
    public $apPaternoContratante = '';
    /** @var string */
    public $noContratante = '';
    /** @var string */
    public $apMaternoContratante = '';
    /** @var string */
    public $tiDocumentoContratante = '';
    /** @var string */
    public $idReContratante = '';
    /** @var string */
    public $nuDocumentoContratante = '';
    /** @var string */
    public $coPaisContratante = '';
}
