<?php

namespace Romeldev\SusaludX12\Beans;

class InConAse270 extends AbstractBean
{
    /** @var string */
    protected $noTransaccion = '';
    /** @var string */
    protected $idRemitente = '';
    /** @var string */
    protected $idReceptor = '';
    /** @var string */
    protected $feTransaccion = '';
    /** @var string */
    protected $hoTransaccion = '';
    /** @var string */
    protected $idCorrelativo = '';
    /** @var string */
    protected $idTransaccion = '';
    /** @var string */
    protected $tiFinalidad = '';
    /** @var string */
    protected $caRemitente = '';
    /** @var string */
    protected $nuRucRemitente = '';
    /** @var string */
    protected $txRequest = '';
    /** @var string */
    protected $caReceptor = '';
    /** @var string */
    protected $caPaciente = '';
    /** @var string */
    protected $apPaternoPaciente = '';
    /** @var string */
    protected $noPaciente = '';
    /** @var string */
    protected $coAfPaciente = '';
    /** @var string */
    protected $apMaternoPaciente = '';
    /** @var string */
    protected $tiDocumento = '';
    /** @var string */
    protected $nuDocumento = '';
    /** @var string */
    protected $coProducto = '';
    /** @var string */
    protected $deProducto = '';
    /** @var string */
    protected $coInProducto = '';
    /** @var string */
    protected $nuCobertura = '';
    /** @var string */
    protected $deCobertura = '';
    /** @var string */
    protected $caServicio = '';
    /** @var string */
    protected $coCalservicio = '';
    /** @var string */
    protected $beMaxInicial = '';
    /** @var string */
    protected $coTiCobertura = '';
    /** @var string */
    protected $coSuTiCobertura = '';
    /** @var string */
    protected $coAplicativoTx = '';
    /** @var string */
    protected $coEspecialidad = '';
    /** @var string */
    protected $coParentesco = '';
    /** @var string */
    protected $nuPlan = '';
    /** @var string */
    protected $nuAutOrigen = '';
    /** @var string */
    protected $tiAccidente = '';
    /** @var string */
    protected $feAccidente = '';
    /** @var string */
    protected $tiCaContratante = '';
    /** @var string */
    protected $noPaContratante = '';
    /** @var string */
    protected $noContratante = '';
    /** @var string */
    protected $noMaContratante = '';
    /** @var string */
    protected $tiDoContratante = '';
    /** @var string */
    protected $idReContratante = '';
    /** @var string */
    protected $coReContratante = '';
    /** @var string */
    protected $nuControl = '';
    /** @var string */
    protected $nuControlST = '';
}
