<?php

namespace Romeldev\SusaludX12\Beans;

class InConAse270
{
    /** @var string */
    public $noTransaccion = '';
    /** @var string */
    public $idRemitente = '';
    /** @var string */
    public $idReceptor = '';
    /** @var string */
    public $feTransaccion = '';
    /** @var string */
    public $hoTransaccion = '';
    /** @var string */
    public $idCorrelativo = '';
    /** @var string */
    public $idTransaccion = '';
    /** @var string */
    public $tiFinalidad = '';
    /** @var string */
    public $caRemitente = '';
    /** @var string */
    public $nuRucRemitente = '';
    /** @var string */
    public $txRequest = '';
    /** @var string */
    public $caReceptor = '';
    /** @var string */
    public $caPaciente = '';
    /** @var string */
    public $apPaternoPaciente = '';
    /** @var string */
    public $noPaciente = '';
    /** @var string */
    public $coAfPaciente = '';
    /** @var string */
    public $apMaternoPaciente = '';
    /** @var string */
    public $tiDocumento = '';
    /** @var string */
    public $nuDocumento = '';
    /** @var string */
    public $coProducto = '';
    /** @var string */
    public $deProducto = '';
    /** @var string */
    public $coInProducto = '';
    /** @var string */
    public $nuCobertura = '';
    /** @var string */
    public $deCobertura = '';
    /** @var string */
    public $caServicio = '';
    /** @var string */
    public $coCalservicio = '';
    /** @var string */
    public $beMaxInicial = '';
    /** @var string */
    public $coTiCobertura = '';
    /** @var string */
    public $coSuTiCobertura = '';
    /** @var string */
    public $coAplicativoTx = '';
    /** @var string */
    public $coEspecialidad = '';
    /** @var string */
    public $coParentesco = '';
    /** @var string */
    public $nuPlan = '';
    /** @var string */
    public $nuAutOrigen = '';
    /** @var string */
    public $tiAccidente = '';
    /** @var string */
    public $feAccidente = '';
    /** @var string */
    public $tiCaContratante = '';
    /** @var string */
    public $noPaContratante = '';
    /** @var string */
    public $noContratante = '';
    /** @var string */
    public $noMaContratante = '';
    /** @var string */
    public $tiDoContratante = '';
    /** @var string */
    public $idReContratante = '';
    /** @var string */
    public $coReContratante = '';
    /** @var string */
    public $nuControl = '';
    /** @var string */
    public $nuControlST = '';
}
