<?php

namespace Romeldev\SusaludX12\Beans;

use Romeldev\SusaludX12\Beans\Detalle\InConCod271Detalle;

class InConCod271
{
    /** @var string */
    public $noTransaccion = '';
    /** @var string */
    public $idRemitente = '';
    /** @var string */
    public $idReceptor = '';
    /** @var string */
    public $feTransaccion = '';
    /** @var string */
    public $hoTransaccion = '';
    /** @var string */
    public $idCorrelativo = '';
    /** @var string */
    public $idTransaccion = '';
    /** @var string */
    public $tiFinalidad = '';
    /** @var string */
    public $caRemitente = '';
    /** @var string */
    public $userRemitente = '';
    /** @var string */
    public $passRemitente = '';
    /** @var string */
    public $feUpFoto = '';
    /** @var string */
    public $caReceptor = '';
    /** @var string */
    public $nuRucReceptor = '';
    /** @var string */
    public $caPaciente = '';
    /** @var string */
    public $apPaternoPaciente = '';
    /** @var string */
    public $noPaciente = '';
    /** @var string */
    public $coAfPaciente = '';
    /** @var string */
    public $apMaternoPaciente = '';
    /** @var string */
    public $coEsPaciente = '';
    /** @var string */
    public $tiDoPaciente = '';
    /** @var string */
    public $nuDoPaciente = '';
    /** @var string */
    public $nuIdenPaciente = '';
    /** @var string */
    public $nuContratoPaciente = '';
    /** @var string */
    public $nuPoliza = '';
    /** @var string */
    public $nuCertificado = '';
    /** @var string */
    public $coTiPoliza = '';
    /** @var string */
    public $coProducto = '';
    /** @var string */
    public $deProducto = '';
    /** @var string */
    public $nuPlan = '';
    /** @var string */
    public $tiPlanSalud = '';
    /** @var string */
    public $coMoneda = '';
    /** @var string */
    public $coParentesco = '';
    /** @var string */
    public $soBeneficio = '';
    /** @var string */
    public $nuSoBeneficio = '';
    /** @var string */
    public $feNacimiento = '';
    /** @var string */
    public $genero = '';
    /** @var string */
    public $esMarital = '';
    /** @var string */
    public $feIniVigencia = '';
    /** @var string */
    public $feFinVigencia = '';
    /** @var string */
    public $tiCaContratante = '';
    /** @var string */
    public $noPaContratante = '';
    /** @var string */
    public $noContratante = '';
    /** @var string */
    public $noMaContratante = '';
    /** @var string */
    public $tiDoContratante = '';
    /** @var string */
    public $idReContratante = '';
    /** @var string */
    public $coReContratante = '';
    /** @var string */
    public $caTitular = '';
    /** @var string */
    public $noPaTitular = '';
    /** @var string */
    public $noTitular = '';
    /** @var string */
    public $coAfTitular = '';
    /** @var string */
    public $noMaTitular = '';
    /** @var string */
    public $tiDoTitular = '';
    /** @var string */
    public $nuDoTitular = '';
    /** @var string */
    public $feInsTitular = '';
    /** @var string */
    public $nuControl = '';
    /** @var string */
    public $nuControlST = '';
    /** @var InConCod271Detalle[] */
    public $inConCod271Detalles = [];
}
