<?php

namespace Romeldev\SusaludX12\Beans;

class InLogAcreInsert271
{
    /** @var string */
    public $noTransaccion = '';
    /** @var string */
    public $idRemitente = '';
    /** @var string */
    public $idReceptor = '';
    /** @var string */
    public $feTransaccion = '';
    /** @var string */
    public $hoTransaccion = '';
    /** @var string */
    public $idCorrelativo = '';
    /** @var string */
    public $idTransaccion = '';
    /** @var string */
    public $tiFinalidad = '';
    /** @var string */
    public $caRemitente = '';
    /** @var string */
    public $nuRucRemitente = '';
    /** @var string */
    public $caReceptor = '';
    /** @var string */
    public $caPaciente = '';
    /** @var string */
    public $apPaternoPaciente = '';
    /** @var string */
    public $noPaciente = '';
    /** @var string */
    public $coAfPaciente = '';
    /** @var string */
    public $apMaternoPaciente = '';
    /** @var string */
    public $coEsPaciente = '';
    /** @var string */
    public $tiDoPaciente = '';
    /** @var string */
    public $nuDoPaciente = '';
    /** @var string */
    public $nuContratoPaciente = '';
    /** @var string */
    public $coTiPolizaAfiliacion = '';
    /** @var string */
    public $coProducto = '';
    /** @var string */
    public $nuPlan = '';
    /** @var string */
    public $coParentesco = '';
    /** @var string */
    public $feNacimiento = '';
    /** @var string */
    public $genero = '';
    /** @var string */
    public $feIniVigencia = '';
    /** @var string */
    public $nuCobertura = '';
    /** @var string */
    public $deCobertura = '';
    /** @var string */
    public $caContratante = '';
    /** @var string */
    public $tiDoContratante = '';
    /** @var string */
    public $idReContratante = '';
    /** @var string */
    public $rucContratante = '';
    /** @var string */
    public $coAfiliadoTitular = '';
    /** @var string */
    public $caResponsableAut = '';
    /** @var string */
    public $noPaResponsableAut = '';
    /** @var string */
    public $noResponsableAut = '';
    /** @var string */
    public $noMaResponsableAut = '';
    /** @var string */
    public $tiDoResponsableAut = '';
    /** @var string */
    public $nuDoResponsableAut = '';
    /** @var string */
    public $nuAutorizacion = '';
    /** @var string */
    public $feHoAutorizacion = '';
    /** @var string */
    public $beMaxInicial = '';
    /** @var string */
    public $coPagoFijo = '';
    /** @var string */
    public $coPagoVariable = '';
    /** @var string */
    public $flagCartaGarantia = '';
    /** @var string */
    public $deFlagCartaGarantia = '';
    /** @var string */
    public $nuControl = '';
    /** @var string */
    public $nuControlST = '';
}
