<?php

namespace Romeldev\SusaludX12\Beans;

class InLogAcreInsert271 extends AbstractBean
{
    /** @var string */
    protected $noTransaccion = '';
    /** @var string */
    protected $idRemitente = '';
    /** @var string */
    protected $idReceptor = '';
    /** @var string */
    protected $feTransaccion = '';
    /** @var string */
    protected $hoTransaccion = '';
    /** @var string */
    protected $idCorrelativo = '';
    /** @var string */
    protected $idTransaccion = '';
    /** @var string */
    protected $tiFinalidad = '';
    /** @var string */
    protected $caRemitente = '';
    /** @var string */
    protected $nuRucRemitente = '';
    /** @var string */
    protected $caReceptor = '';
    /** @var string */
    protected $caPaciente = '';
    /** @var string */
    protected $apPaternoPaciente = '';
    /** @var string */
    protected $noPaciente = '';
    /** @var string */
    protected $coAfPaciente = '';
    /** @var string */
    protected $apMaternoPaciente = '';
    /** @var string */
    protected $coEsPaciente = '';
    /** @var string */
    protected $tiDoPaciente = '';
    /** @var string */
    protected $nuDoPaciente = '';
    /** @var string */
    protected $nuContratoPaciente = '';
    /** @var string */
    protected $coTiPolizaAfiliacion = '';
    /** @var string */
    protected $coProducto = '';
    /** @var string */
    protected $nuPlan = '';
    /** @var string */
    protected $coParentesco = '';
    /** @var string */
    protected $feNacimiento = '';
    /** @var string */
    protected $genero = '';
    /** @var string */
    protected $feIniVigencia = '';
    /** @var string */
    protected $nuCobertura = '';
    /** @var string */
    protected $deCobertura = '';
    /** @var string */
    protected $caContratante = '';
    /** @var string */
    protected $tiDoContratante = '';
    /** @var string */
    protected $idReContratante = '';
    /** @var string */
    protected $rucContratante = '';
    /** @var string */
    protected $coAfiliadoTitular = '';
    /** @var string */
    protected $caResponsableAut = '';
    /** @var string */
    protected $noPaResponsableAut = '';
    /** @var string */
    protected $noResponsableAut = '';
    /** @var string */
    protected $noMaResponsableAut = '';
    /** @var string */
    protected $tiDoResponsableAut = '';
    /** @var string */
    protected $nuDoResponsableAut = '';
    /** @var string */
    protected $nuAutorizacion = '';
    /** @var string */
    protected $feHoAutorizacion = '';
    /** @var string */
    protected $beMaxInicial = '';
    /** @var string */
    protected $coPagoFijo = '';
    /** @var string */
    protected $coPagoVariable = '';
    /** @var string */
    protected $flagCartaGarantia = '';
    /** @var string */
    protected $deFlagCartaGarantia = '';
    /** @var string */
    protected $nuControl = '';
    /** @var string */
    protected $nuControlST = '';
}
