<?php

namespace Romeldev\SusaludX12\Beans;

use Romeldev\SusaludX12\Beans\Detalle\InSolAutExeCar271Detalle;
use Romeldev\SusaludX12\Beans\Detalle\InSolAutProEsp271Detalle;
use Romeldev\SusaludX12\Beans\Detalle\InSolAutRes271Detalle;
use Romeldev\SusaludX12\Beans\Detalle\InSolAutTieEsp271Detalle;

class InSolAut271
{
    /** @var string */
    public $noTransaccion = '';
    /** @var string */
    public $idRemitente = '';
    /** @var string */
    public $idReceptor = '';
    /** @var string */
    public $feTransaccion = '';
    /** @var string */
    public $hoTransaccion = '';
    /** @var string */
    public $idCorrelativo = '';
    /** @var string */
    public $idTransaccion = '';
    /** @var string */
    public $tiFinalidad = '';
    /** @var string */
    public $caRemitente = '';
    /** @var string */
    public $nuRucRemitente = '';
    /** @var string */
    public $caReceptor = '';
    /** @var string */
    public $coAdmisionista = '';
    /** @var string */
    public $caPaciente = '';
    /** @var string */
    public $apPaternoPaciente = '';
    /** @var string */
    public $noPaciente = '';
    /** @var string */
    public $coAfPaciente = '';
    /** @var string */
    public $apMaternoPaciente = '';
    /** @var string */
    public $coEsPaciente = '';
    /** @var string */
    public $tiDoPaciente = '';
    /** @var string */
    public $nuDoPaciente = '';
    /** @var string */
    public $nuIdenEmpleador = '';
    /** @var string */
    public $nuContratoPaciente = '';
    /** @var string */
    public $nuPoliza = '';
    /** @var string */
    public $nuCertificado = '';
    /** @var string */
    public $coTiPolizaAfiliacion = '';
    /** @var string */
    public $coProducto = '';
    /** @var string */
    public $deProducto = '';
    /** @var string */
    public $nuPlan = '';
    /** @var string */
    public $tiPlanSalud = '';
    /** @var string */
    public $coMoneda = '';
    /** @var string */
    public $coParentesco = '';
    /** @var string */
    public $soBeneficio = '';
    /** @var string */
    public $nuSoBeneficio = '';
    /** @var string */
    public $coEspecialidad = '';
    /** @var string */
    public $feNacimiento = '';
    /** @var string */
    public $genero = '';
    /** @var string */
    public $esMarital = '';
    /** @var string */
    public $feIniVigencia = '';
    /** @var string */
    public $feFinVigencia = '';
    /** @var string */
    public $esCobertura = '';
    /** @var string */
    public $nuDecAccidente = '';
    /** @var string */
    public $idInfAccidente = '';
    /** @var string */
    public $deTiAccidente = '';
    /** @var string */
    public $feAfiliacion = '';
    /** @var string */
    public $feOcuAccidente = '';
    /** @var string */
    public $nuAtencion = '';
    /** @var string */
    public $idDerFarmacia = '';
    /** @var string */
    public $tiProducto = '';
    /** @var string */
    public $deProductoDeFarmacia = '';
    /** @var string */
    public $feAtencion = '';
    /** @var string */
    public $nuCobertura = '';
    /** @var string */
    public $obsCobertura = '';
    /** @var string */
    public $msgObs = '';
    /** @var string */
    public $msgConEspeciales = '';
    /** @var string */
    public $caContratante = '';
    /** @var string */
    public $noPaContratante = '';
    /** @var string */
    public $noContratante = '';
    /** @var string */
    public $noMaContratante = '';
    /** @var string */
    public $tiDoContratante = '';
    /** @var string */
    public $idReContratante = '';
    /** @var string */
    public $coReContratante = '';
    /** @var string */
    public $caTitular = '';
    /** @var string */
    public $noPaTitular = '';
    /** @var string */
    public $noTitular = '';
    /** @var string */
    public $coAfTitular = '';
    /** @var string */
    public $noMaTitular = '';
    /** @var string */
    public $tiDoTitular = '';
    /** @var string */
    public $idReTitular = '';
    /** @var string */
    public $nuDoTitular = '';
    /** @var string */
    public $feIncTitular = '';
    /** @var string */
    public $nuCobPreExistencia = '';
    /** @var string */
    public $beMaxInicial = '';
    /** @var string */
    public $canServicio = '';
    /** @var string */
    public $idDeProducto = '';
    /** @var string */
    public $coTiCobertura = '';
    /** @var string */
    public $coSubTiCobertura = '';
    /** @var string */
    public $msgObsPre = '';
    /** @var string */
    public $msgConEspecialesPre = '';
    /** @var string */
    public $coTiMoneda = '';
    /** @var string */
    public $coPagoFijo = '';
    /** @var string */
    public $coCalServicio = '';
    /** @var string */
    public $canCalServicio = '';
    /** @var string */
    public $coPagoVariable = '';
    /** @var string */
    public $flagCG = '';
    /** @var string */
    public $deflagCG = '';
    /** @var string */
    public $feFinCarencia = '';
    /** @var string */
    public $feFinEspera = '';
    /** @var InSolAutProEsp271Detalle[] */
    public $inSolAutProEsp271Detalle = [];
    /** @var InSolAutTieEsp271Detalle[] */
    public $inSolAutTieEsp271Detalle = [];
    /** @var InSolAutExeCar271Detalle[] */
    public $inSolAutExeCar271Detalle = [];
    /** @var InSolAutRes271Detalle[] */
    public $inSolAut271Detalle = [];
    /** @var string */
    public $caRegafi = '';
    /** @var string */
    public $noPaRegafi = '';
    /** @var string */
    public $noRegafi = '';
    /** @var string */
    public $coAfRegafi = '';
    /** @var string */
    public $noMaRegafi = '';
    /** @var string */
    public $tiDoRegafi = '';
    /** @var string */
    public $idReRegafi = '';
    /** @var string */
    public $nuDoRegafi = '';
    /** @var string */
    public $feNaRegafi = '';
    /** @var string */
    public $geRegafi = '';
    /** @var string */
    public $coPaisRegafi = '';
    /** @var string */
    public $nuControl = '';
    /** @var string */
    public $nuControlST = '';
}
